part of 'sviper.dart';

/// Base class for Widget module builder
abstract class SviperWidget extends StatefulWidget {
  /// This method returns the Input.
  Object getInput();

  /// Default constructor
  const SviperWidget({
    super.key,
  });

  @override
  @protected
  // ignore: no_logic_in_create_state
  State<StatefulWidget> createState() => buildView();

  /// This method should return the View for the module.
  @protected
  @factory
  State<StatefulWidget> buildView();

  /// This method will be generated by the code generator.
  SviperPresenter buildConfiguration(SviperView view);
}

/// Base class for Page module builder
abstract class SviperPage<Output> extends SviperWidget {
  final String name;
  final Object _input;

  /// This method returns the Input.
  @override
  Object getInput() => _input;

  /// Default constructor
  const SviperPage(
    this._input, {
    super.key,
    required this.name,
  });
}
