name: sviper
description: Sviper is an architectural pattern for Flutter projects, inspired by the VIPER architecture.
repository: https://github.com/siqwin/sviper
version: 1.1.10

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
