name: sviper_generator
description: Generator for Sviper (architectural pattern for Flutter projects, inspired by the VIPER architecture).
repository: https://github.com/siqwin/sviper
version: 1.1.10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.1.0 <7.0.0"
  build: ^2.1.1
  build_test: ^2.1.6
  built_collection: ^5.0.0
  code_builder: ^4.2.0
  collection: ^1.0.0
  dart_style: ^2.0.0
  path: ^1.6.0
  recase: ^4.1.0
  source_gen: ^1.2.3
  sviper: ^1.1.7