name: Publish sviper_generator to pub.dev

on:
  push:
    tags:
      - 'sviper_generator-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    environment: pub.dev
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"
      - uses: dart-lang/setup-dart@v1
      - name: Install dependencies
        working-directory: sviper_generator
        run: dart pub get
      - name: Dart format
        working-directory: sviper_generator
        run: dart format .
      - name: Publish
        working-directory: sviper_generator
        run: dart pub publish --force