name: Publish sviper to pub.dev

on:
  push:
    tags:
      - 'sviper-v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
       working-directory: sviper